name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |    
         git fetch --no-tags --prune --depth=100 origin +refs/heads/*:refs/remotes/origin/*

      # - name: Cache setup
      #   uses: actions/cache@v1
      #   env:
      #     cache-name: cache-bioconda-utils
      #   with:
      #     path: ~/miniconda
      #   key: ${{ env.cache-name }}-${{ hashFiles('.github/setup.sh') }}
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: setup
        shell: bash -l {0}
        run: .github/setup.sh
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v1
      - name: lint
        shell: bash -l {0}
        run: |
          bioconda-utils lint tools config.yml --exclude missing_hash missing_tests --git-range origin/master HEAD
#       - name: build
#         shell: bash -l {0}
#         run: |
#           bioconda-utils build tools config.yml --git-range origin/master HEAD
